<?php get_header(); ?>

<div id="content" class="clearfix row">
  <div id="main" class="col-md-8 clearfix" role="main">
    <div class="media-list">
      <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
      <section class="post_content">
        <?php get_template_part( 'content', 'event'); ?>
      </section> <!-- end article section -->
      <?php endwhile; ?>	
    </div>

    <?php if (function_exists('wp_bootstrap_page_navi')) { // if expirimental feature is active ?>

    <?php wp_bootstrap_page_navi(); // use the page navi function ?>

    <?php } else { // if it is disabled, display regular wp prev & next links ?>
    <nav class="wp-prev-next">
      <ul class="pager">
        <li class="previous"><?php next_posts_link(_e('&laquo; Older Entries', "wpbootstrap")) ?></li>
        <li class="next"><?php previous_posts_link(_e('Newer Entries &raquo;', "wpbootstrap")) ?></li>
      </ul>
    </nav>
    <?php } ?>		

    <?php else : ?>

    <article id="post-not-found">
      <header>
        <h1><?php _e("Not Found", "wpbootstrap"); ?></h1>
      </header>
      <section class="post_content">
        <p><?php _e("Sorry, but the requested resource was not found on this site.", "wpbootstrap"); ?></p>
      </section>
      <footer>
      </footer>
    </article>

    <?php endif; ?>

  </div> <!-- end #main -->

  <?php get_sidebar(); // sidebar 1 ?>

</div> <!-- end #content -->

<?php get_footer(); ?>
